services:
  ai-nutrition:
    build: .
    container_name: mspr-ai-nutrition
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - mspr_data_network
      - internal

  ollama:
    image: ollama/ollama:latest
    container_name: mspr-ollama
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - internal
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull gemma3:4b && wait"]

networks:
  mspr_data_network:
    external: true
  internal:
    driver: bridge

volumes:
  ollama_data:
