"""Genere app/data/fallback_plans.json (16 plans : 4 health_goal x 4 diet_type).

Le JSON produit est commite et sert de fallback quand Ollama est indisponible.
Lancer ce script si on modifie les pools de repas ou la matrice.
"""

from __future__ import annotations

import json
from pathlib import Path

# Slots de repas par objectif sante (regle PRD).
SLOTS = {
    "weight_loss": ["breakfast", "lunch", "dinner"],
    "balance": ["breakfast", "lunch", "dinner"],
    "sport_performance": ["breakfast", "lunch", "snack_pm", "dinner"],
    "muscle_gain": ["breakfast", "snack_am", "lunch", "snack_pm", "dinner"],
}

HEALTH_GOALS = ["weight_loss", "muscle_gain", "balance", "sport_performance"]
DIET_TYPES = ["omnivore", "vegetarien", "vegan", "sans_gluten"]


def _meal(name, calories, protein, carbs, fat, ingredients, budget, prep):
    return {
        "name": name,
        "macros": {
            "calories": calories,
            "protein_g": protein,
            "carbs_g": carbs,
            "fat_g": fat,
        },
        "ingredients": ingredients,
        "est_budget_eur": budget,
        "prep_time_min": prep,
    }


# Pools par (diet_type, slot). 7 entrees -> 1 par jour.

POOLS: dict[tuple[str, str], list[dict]] = {
    # omnivore
    ("omnivore", "breakfast"): [
        _meal("Yaourt grec granola fruits rouges", 380, 22, 45, 11,
              ["yaourt grec nature", "granola avoine", "fruits rouges", "miel", "amandes effilees"],
              2.20, 5),
        _meal("Omelette aux legumes et pain complet", 450, 28, 32, 22,
              ["oeufs", "courgette", "tomate", "fromage rape", "pain complet", "beurre"],
              2.40, 12),
        _meal("Porridge avoine banane", 420, 16, 60, 13,
              ["flocons d'avoine", "lait demi-ecreme", "banane", "beurre de cacahuete", "miel"],
              1.80, 8),
        _meal("Pancakes proteines", 460, 26, 50, 14,
              ["oeufs", "flocons d'avoine", "banane", "sirop d'erable", "fruits rouges"],
              2.30, 15),
        _meal("Tartines avocat saumon fume", 480, 24, 38, 22,
              ["pain complet", "avocat", "saumon fume", "citron", "graines de sesame"],
              3.50, 7),
        _meal("Smoothie bowl banane fruits rouges", 410, 14, 60, 12,
              ["banane", "fruits rouges", "lait demi-ecreme", "granola avoine", "graines de chia"],
              2.10, 6),
        _meal("Oeufs brouilles tomate fromage", 440, 26, 28, 24,
              ["oeufs", "beurre", "pain complet", "fromage rape", "tomate", "ciboulette"],
              2.20, 10),
    ],
    ("omnivore", "lunch"): [
        _meal("Salade poulet quinoa feta", 580, 38, 55, 22,
              ["blanc de poulet grille", "quinoa", "tomates cerises", "concombre", "feta", "huile d'olive"],
              4.20, 20),
        _meal("Wrap dinde crudites", 540, 32, 50, 20,
              ["tortilla ble", "blanc de dinde", "salade", "tomate", "fromage frais", "avocat"],
              3.80, 10),
        _meal("Bowl saumon riz complet", 620, 36, 60, 22,
              ["saumon", "riz complet", "edamame", "avocat", "graines de sesame", "sauce soja"],
              5.50, 25),
        _meal("Pates bolognaise maison", 650, 35, 70, 22,
              ["pates completes", "boeuf hache", "sauce tomate", "parmesan", "oignon", "huile d'olive"],
              3.40, 30),
        _meal("Salade nicoise", 520, 30, 35, 26,
              ["thon", "oeuf dur", "haricots verts", "pommes de terre", "olives noires", "tomate"],
              3.90, 25),
        _meal("Risotto poulet champignons", 600, 34, 65, 20,
              ["riz arborio", "blanc de poulet", "champignons de Paris", "parmesan", "oignon", "bouillon de volaille"],
              4.30, 35),
        _meal("Bol mexicain boeuf", 590, 34, 55, 24,
              ["riz", "boeuf hache", "haricots rouges", "mais", "avocat", "salsa"],
              3.80, 25),
    ],
    ("omnivore", "dinner"): [
        _meal("Saumon grille legumes patate douce", 560, 36, 45, 25,
              ["saumon", "brocoli", "patate douce", "huile d'olive", "citron", "ail"],
              5.80, 30),
        _meal("Poulet roti riz et courgettes", 540, 38, 55, 16,
              ["blanc de poulet", "courgette", "poivron", "oignon", "riz", "herbes de Provence"],
              3.90, 35),
        _meal("Cabillaud haricots verts", 480, 34, 38, 18,
              ["cabillaud", "haricots verts", "pommes de terre vapeur", "citron", "persil", "huile d'olive"],
              5.20, 25),
        _meal("Boeuf saute legumes asiatiques", 600, 38, 50, 24,
              ["boeuf", "brocoli", "poivron rouge", "riz", "sauce soja", "gingembre"],
              4.80, 25),
        _meal("Curry de poulet riz basmati", 580, 35, 55, 22,
              ["blanc de poulet", "lait de coco", "pate de curry", "riz basmati", "oignon", "tomate"],
              4.20, 30),
        _meal("Lasagnes maison salade", 640, 34, 60, 28,
              ["pates a lasagnes", "boeuf hache", "sauce tomate", "bechamel", "parmesan", "salade verte"],
              4.10, 50),
        _meal("Tajine agneau semoule", 620, 36, 65, 22,
              ["agneau", "abricots secs", "oignon", "semoule de ble", "amandes", "epices ras el hanout"],
              5.50, 60),
    ],
    ("omnivore", "snack_am"): [
        _meal("Banane et beurre de cacahuete", 280, 8, 35, 12,
              ["banane", "beurre de cacahuete"], 0.80, 2),
        _meal("Skyr fruits rouges", 220, 22, 24, 4,
              ["skyr", "fruits rouges", "miel"], 1.80, 3),
        _meal("Smoothie proteine", 320, 22, 38, 9,
              ["lait demi-ecreme", "banane", "fruits rouges", "proteine whey", "miel"], 2.20, 4),
        _meal("Toast avocat oeuf", 340, 14, 30, 18,
              ["pain complet", "avocat", "oeuf poche", "graines de sesame"], 1.80, 8),
        _meal("Yaourt grec amandes miel", 280, 14, 22, 14,
              ["yaourt grec nature", "amandes", "miel"], 1.50, 2),
        _meal("Cottage cheese ananas", 240, 22, 24, 4,
              ["cottage cheese", "ananas frais", "miel"], 2.10, 3),
        _meal("Fruits secs et noix", 300, 8, 32, 16,
              ["noix", "amandes", "raisins secs", "abricots secs"], 1.80, 1),
    ],
    ("omnivore", "snack_pm"): [
        _meal("Pomme et amandes", 240, 6, 30, 12,
              ["pomme", "amandes"], 0.80, 1),
        _meal("Skyr fruits frais", 220, 22, 24, 4,
              ["skyr", "myrtilles", "miel"], 1.80, 3),
        _meal("Tartines fromage frais", 320, 14, 36, 12,
              ["pain complet", "fromage frais", "concombre", "ciboulette"], 1.80, 5),
        _meal("Smoothie banane lait", 280, 14, 38, 7,
              ["lait demi-ecreme", "banane", "miel", "cannelle"], 1.20, 3),
        _meal("Yaourt grec granola", 300, 16, 30, 12,
              ["yaourt grec nature", "granola avoine", "miel"], 1.80, 2),
        _meal("Houmous et legumes", 260, 8, 28, 14,
              ["houmous", "carottes", "concombre", "pain complet"], 1.80, 5),
        _meal("Oeufs durs et fruits", 240, 16, 22, 10,
              ["oeufs durs", "pomme", "amandes"], 1.50, 8),
    ],

    # vegetarien (sans viande ni poisson)
    ("vegetarien", "breakfast"): [
        _meal("Yaourt grec granola fruits rouges", 380, 22, 45, 11,
              ["yaourt grec nature", "granola avoine", "fruits rouges", "miel", "amandes effilees"],
              2.20, 5),
        _meal("Omelette aux legumes pain complet", 450, 26, 32, 22,
              ["oeufs", "courgette", "tomate", "fromage rape", "pain complet", "beurre"],
              2.40, 12),
        _meal("Porridge avoine banane", 420, 16, 60, 13,
              ["flocons d'avoine", "lait demi-ecreme", "banane", "beurre de cacahuete", "miel"],
              1.80, 8),
        _meal("Pancakes proteines", 460, 24, 52, 14,
              ["oeufs", "flocons d'avoine", "banane", "sirop d'erable", "fruits rouges"],
              2.30, 15),
        _meal("Tartines avocat fromage frais", 440, 18, 42, 22,
              ["pain complet", "avocat", "fromage frais", "tomate", "graines de sesame"],
              2.40, 7),
        _meal("Smoothie bowl banane fruits rouges", 410, 14, 60, 12,
              ["banane", "fruits rouges", "lait demi-ecreme", "granola avoine", "graines de chia"],
              2.10, 6),
        _meal("Oeufs brouilles tomate fromage", 440, 24, 28, 24,
              ["oeufs", "beurre", "pain complet", "fromage rape", "tomate", "ciboulette"],
              2.20, 10),
    ],
    ("vegetarien", "lunch"): [
        _meal("Salade quinoa feta pois chiches", 560, 22, 60, 22,
              ["quinoa", "feta", "pois chiches", "tomates cerises", "concombre", "huile d'olive"],
              3.40, 20),
        _meal("Wrap fromage avocat crudites", 520, 18, 55, 22,
              ["tortilla ble", "fromage", "salade", "tomate", "avocat", "houmous"],
              3.20, 10),
        _meal("Bowl tofu riz complet", 580, 28, 62, 20,
              ["tofu ferme", "riz complet", "edamame", "avocat", "graines de sesame", "sauce soja"],
              3.80, 25),
        _meal("Pates pesto mozzarella", 620, 24, 70, 24,
              ["pates completes", "pesto basilic", "tomates cerises", "mozzarella", "parmesan", "huile d'olive"],
              3.10, 20),
        _meal("Salade chevre miel noix", 540, 22, 35, 30,
              ["salade verte", "chevre", "noix", "miel", "pain complet", "vinaigrette"],
              3.60, 15),
        _meal("Risotto champignons parmesan", 580, 18, 70, 22,
              ["riz arborio", "champignons", "parmesan", "oignon", "bouillon legumes", "beurre"],
              3.30, 35),
        _meal("Quiche legumes salade", 560, 20, 50, 26,
              ["pate brisee", "oeufs", "courgette", "fromage rape", "creme", "salade verte"],
              3.20, 45),
    ],
    ("vegetarien", "dinner"): [
        _meal("Curry pois chiches lait coco", 540, 22, 65, 20,
              ["pois chiches", "lait de coco", "pate de curry", "riz basmati", "oignon", "tomate"],
              2.80, 30),
        _meal("Tarte legumes salade", 520, 20, 45, 26,
              ["pate brisee", "courgette", "tomate", "oeuf", "fromage de chevre", "salade"],
              3.40, 50),
        _meal("Lasagnes vegetariennes", 600, 24, 60, 26,
              ["pates a lasagnes", "ricotta", "epinards", "sauce tomate", "parmesan", "bechamel"],
              3.60, 60),
        _meal("Buddha bowl complet", 560, 22, 65, 18,
              ["quinoa", "patate douce roti", "brocoli", "oeuf", "avocat", "sauce tahini"],
              3.20, 30),
        _meal("Poelee tofu legumes asiatiques", 520, 26, 55, 18,
              ["tofu ferme", "brocoli", "poivron rouge", "riz", "sauce soja", "gingembre"],
              3.40, 25),
        _meal("Pizza vegetarienne maison", 640, 24, 70, 26,
              ["pate a pizza", "sauce tomate", "mozzarella", "champignons", "olives", "basilic"],
              3.20, 30),
        _meal("Gratin courgettes oeufs", 540, 22, 35, 30,
              ["courgette", "oeufs", "fromage rape", "creme", "herbes de Provence", "pain complet"],
              2.80, 45),
    ],
    ("vegetarien", "snack_am"): [
        _meal("Banane et beurre de cacahuete", 280, 8, 35, 12,
              ["banane", "beurre de cacahuete"], 0.80, 2),
        _meal("Skyr fruits rouges", 220, 22, 24, 4,
              ["skyr", "fruits rouges", "miel"], 1.80, 3),
        _meal("Smoothie proteine vegetarien", 300, 18, 38, 9,
              ["lait demi-ecreme", "banane", "fruits rouges", "proteine whey", "miel"], 2.20, 4),
        _meal("Toast avocat oeuf", 340, 14, 30, 18,
              ["pain complet", "avocat", "oeuf poche", "graines de sesame"], 1.80, 8),
        _meal("Yaourt grec amandes miel", 280, 14, 22, 14,
              ["yaourt grec nature", "amandes", "miel"], 1.50, 2),
        _meal("Cottage cheese ananas", 240, 22, 24, 4,
              ["cottage cheese", "ananas frais", "miel"], 2.10, 3),
        _meal("Fruits secs et noix", 300, 8, 32, 16,
              ["noix", "amandes", "raisins secs", "abricots secs"], 1.80, 1),
    ],
    ("vegetarien", "snack_pm"): [
        _meal("Pomme et amandes", 240, 6, 30, 12,
              ["pomme", "amandes"], 0.80, 1),
        _meal("Skyr fruits frais", 220, 22, 24, 4,
              ["skyr", "myrtilles", "miel"], 1.80, 3),
        _meal("Tartines fromage frais concombre", 320, 14, 36, 12,
              ["pain complet", "fromage frais", "concombre", "ciboulette"], 1.80, 5),
        _meal("Smoothie banane lait", 280, 14, 38, 7,
              ["lait demi-ecreme", "banane", "miel", "cannelle"], 1.20, 3),
        _meal("Yaourt grec granola miel", 300, 16, 30, 12,
              ["yaourt grec nature", "granola avoine", "miel"], 1.80, 2),
        _meal("Houmous et legumes", 260, 8, 28, 14,
              ["houmous", "carottes", "concombre", "pain complet"], 1.80, 5),
        _meal("Oeufs durs pomme amandes", 240, 16, 22, 10,
              ["oeufs durs", "pomme", "amandes"], 1.50, 8),
    ],

    # vegan (rien d'origine animale)
    ("vegan", "breakfast"): [
        _meal("Porridge avoine vegan banane", 420, 12, 65, 12,
              ["flocons d'avoine", "lait d'amande", "banane", "beurre de cacahuete", "sirop d'erable"],
              1.80, 8),
        _meal("Smoothie bowl banane fruits rouges", 400, 12, 60, 12,
              ["banane", "fruits rouges", "lait de soja", "granola avoine", "graines de chia"],
              2.10, 6),
        _meal("Tartines avocat tofu fume", 460, 22, 38, 22,
              ["pain complet", "avocat", "tofu fume", "tomate", "graines de sesame"],
              2.80, 7),
        _meal("Pancakes vegan banane", 420, 10, 65, 12,
              ["farine de ble", "lait de soja", "banane", "sirop d'erable", "fruits rouges"],
              2.10, 15),
        _meal("Bircher muesli avoine", 440, 12, 60, 16,
              ["flocons d'avoine", "lait d'avoine", "pomme rapee", "raisins secs", "noix"],
              2.20, 10),
        _meal("Tartines houmous concombre", 410, 14, 50, 16,
              ["pain complet", "houmous", "tomate", "concombre", "graines de tournesol"],
              1.90, 8),
        _meal("Bowl chia mangue coco", 440, 10, 55, 18,
              ["graines de chia", "lait de coco", "mangue", "noix de coco rapee", "sirop d'erable"],
              2.40, 5),
    ],
    ("vegan", "lunch"): [
        _meal("Salade quinoa pois chiches", 560, 22, 65, 20,
              ["quinoa", "pois chiches", "tomates cerises", "concombre", "olives noires", "huile d'olive", "citron"],
              2.80, 20),
        _meal("Wrap houmous crudites", 520, 16, 65, 20,
              ["tortilla ble", "houmous", "salade", "tomate", "avocat", "carottes rapees"],
              2.40, 10),
        _meal("Bowl tofu riz complet", 580, 28, 60, 22,
              ["tofu ferme", "riz complet", "edamame", "avocat", "graines de sesame", "sauce soja"],
              3.20, 25),
        _meal("Pates lentilles tomate", 600, 26, 75, 16,
              ["pates completes", "sauce tomate", "lentilles corail", "levure maltee", "basilic", "huile d'olive"],
              2.40, 25),
        _meal("Burger lentilles maison", 580, 22, 65, 22,
              ["pain burger", "galette de lentilles", "salade", "tomate", "avocat", "oignon rouge"],
              3.10, 35),
        _meal("Salade falafels houmous", 560, 22, 65, 22,
              ["salade verte", "falafels pois chiches", "tomates", "concombre", "houmous", "pain complet"],
              3.30, 20),
        _meal("Risotto champignons vegan", 540, 16, 70, 18,
              ["riz arborio", "champignons", "levure maltee", "oignon", "bouillon de legumes", "huile d'olive"],
              2.90, 35),
    ],
    ("vegan", "dinner"): [
        _meal("Curry pois chiches lait coco", 540, 20, 70, 18,
              ["pois chiches", "lait de coco", "pate de curry", "riz basmati", "oignon", "tomate"],
              2.80, 30),
        _meal("Buddha bowl vegan", 540, 22, 65, 18,
              ["quinoa", "patate douce roti", "brocoli", "pois chiches", "avocat", "sauce tahini"],
              3.10, 30),
        _meal("Lasagnes lentilles", 580, 24, 70, 18,
              ["pates a lasagnes", "lentilles", "sauce tomate", "bechamel vegetal", "levure maltee"],
              3.20, 60),
        _meal("Poelee tofu legumes asiatiques", 520, 26, 55, 18,
              ["tofu ferme", "brocoli", "poivron rouge", "riz", "sauce soja", "gingembre"],
              2.80, 25),
        _meal("Pizza vegan champignons", 600, 18, 75, 22,
              ["pate a pizza", "sauce tomate", "fromage vegetal rape", "champignons", "olives", "basilic"],
              3.20, 30),
        _meal("Couscous legumes pois chiches", 560, 20, 75, 16,
              ["semoule de ble", "pois chiches", "courgette", "carotte", "navet", "tomate", "epices"],
              2.40, 40),
        _meal("Dahl lentilles riz", 540, 22, 75, 14,
              ["lentilles corail", "riz basmati", "lait de coco", "tomate", "oignon", "epices"],
              2.10, 35),
    ],
    ("vegan", "snack_am"): [
        _meal("Banane et beurre de cacahuete", 280, 8, 35, 12,
              ["banane", "beurre de cacahuete"], 0.80, 2),
        _meal("Smoothie soja fruits rouges", 280, 12, 38, 8,
              ["lait de soja", "banane", "fruits rouges", "graines de chia", "sirop d'erable"], 2.20, 4),
        _meal("Toast avocat houmous", 320, 10, 35, 16,
              ["pain complet", "avocat", "houmous", "graines de sesame"], 1.60, 5),
        _meal("Fruits secs et noix", 300, 8, 32, 16,
              ["noix", "amandes", "raisins secs", "abricots secs"], 1.80, 1),
        _meal("Compote pomme amandes", 240, 6, 32, 12,
              ["compote de pommes", "amandes", "cannelle"], 1.20, 1),
        _meal("Energy balls dattes", 290, 8, 38, 12,
              ["dattes", "amandes", "noix de coco rapee", "cacao"], 2.00, 10),
        _meal("Yaourt soja granola", 280, 10, 38, 10,
              ["yaourt soja nature", "granola avoine", "fruits rouges", "sirop d'erable"], 2.10, 2),
    ],
    ("vegan", "snack_pm"): [
        _meal("Pomme et amandes", 240, 6, 30, 12,
              ["pomme", "amandes"], 0.80, 1),
        _meal("Smoothie banane lait soja", 260, 10, 38, 7,
              ["lait de soja", "banane", "sirop d'erable", "cannelle"], 1.20, 3),
        _meal("Tartines avocat tomate", 320, 8, 38, 14,
              ["pain complet", "avocat", "tomate", "huile d'olive", "graines de sesame"], 1.80, 5),
        _meal("Houmous et crudites", 260, 8, 28, 14,
              ["houmous", "carottes", "concombre", "pain complet"], 1.80, 5),
        _meal("Bowl chia banane", 290, 8, 38, 12,
              ["graines de chia", "lait d'amande", "banane", "sirop d'erable"], 1.90, 5),
        _meal("Energy balls cacao", 280, 8, 36, 12,
              ["dattes", "noix", "cacao", "noix de coco rapee"], 2.00, 10),
        _meal("Pomme beurre de cacahuete", 260, 8, 30, 14,
              ["pomme", "beurre de cacahuete"], 1.00, 2),
    ],

    # sans_gluten (pas de ble, pates, semoule, pain classique). Viande/poisson/laitage/oeuf ok.
    ("sans_gluten", "breakfast"): [
        _meal("Yaourt grec fruits rouges amandes", 380, 22, 38, 14,
              ["yaourt grec nature", "fruits rouges", "miel", "amandes effilees", "graines de chia"],
              2.30, 4),
        _meal("Omelette legumes fromage", 460, 28, 12, 32,
              ["oeufs", "courgette", "tomate", "fromage rape", "beurre", "ciboulette"],
              2.30, 12),
        _meal("Porridge sarrasin banane", 420, 16, 60, 12,
              ["flocons de sarrasin", "lait demi-ecreme", "banane", "beurre de cacahuete", "miel"],
              2.10, 8),
        _meal("Pancakes sarrasin banane", 440, 22, 55, 14,
              ["farine de sarrasin", "oeufs", "lait demi-ecreme", "banane", "sirop d'erable"],
              2.50, 15),
        _meal("Galettes mais avocat oeuf", 460, 22, 42, 22,
              ["galettes de mais", "avocat", "fromage frais", "oeuf poche", "tomate"],
              2.40, 10),
        _meal("Smoothie bowl granola sans gluten", 410, 14, 56, 14,
              ["banane", "fruits rouges", "lait demi-ecreme", "granola sans gluten", "graines de chia"],
              2.60, 6),
        _meal("Bowl quinoa fruits rouges", 420, 14, 60, 14,
              ["quinoa", "lait demi-ecreme", "banane", "fruits rouges", "miel", "amandes effilees"],
              2.40, 15),
    ],
    ("sans_gluten", "lunch"): [
        _meal("Salade poulet quinoa feta", 580, 38, 50, 22,
              ["blanc de poulet grille", "quinoa", "tomates cerises", "concombre", "feta", "huile d'olive"],
              4.20, 20),
        _meal("Bol mexicain riz haricots", 560, 30, 60, 22,
              ["riz", "haricots rouges", "blanc de poulet", "mais", "avocat", "salsa", "fromage rape"],
              3.80, 25),
        _meal("Bowl saumon riz complet", 620, 36, 55, 24,
              ["saumon", "riz complet", "edamame", "avocat", "graines de sesame", "sauce tamari"],
              5.50, 25),
        _meal("Galettes sarrasin oeuf jambon", 540, 28, 50, 22,
              ["galettes de sarrasin", "oeuf", "jambon", "fromage rape", "salade verte"],
              3.40, 15),
        _meal("Risotto poulet champignons", 600, 34, 70, 18,
              ["riz arborio", "blanc de poulet", "champignons", "parmesan", "oignon", "bouillon de volaille"],
              4.30, 35),
        _meal("Salade nicoise sans gluten", 520, 30, 35, 26,
              ["thon", "oeuf dur", "haricots verts", "pommes de terre", "olives noires", "tomate"],
              3.90, 25),
        _meal("Bowl quinoa boeuf legumes", 580, 34, 55, 22,
              ["quinoa", "boeuf grille", "courgette grillee", "poivron grille", "feta", "huile d'olive"],
              4.50, 30),
    ],
    ("sans_gluten", "dinner"): [
        _meal("Saumon grille legumes patate douce", 560, 36, 45, 25,
              ["saumon", "brocoli", "patate douce", "huile d'olive", "citron", "ail"],
              5.80, 30),
        _meal("Poulet roti riz courgettes", 540, 38, 55, 16,
              ["blanc de poulet", "courgette", "poivron", "oignon", "riz", "herbes de Provence"],
              3.90, 35),
        _meal("Cabillaud haricots verts", 480, 34, 38, 18,
              ["cabillaud", "haricots verts", "pommes de terre vapeur", "citron", "persil", "huile d'olive"],
              5.20, 25),
        _meal("Boeuf saute legumes asiatiques", 600, 38, 50, 24,
              ["boeuf", "brocoli", "poivron rouge", "riz", "sauce tamari", "gingembre"],
              4.80, 25),
        _meal("Curry poulet riz basmati", 580, 35, 55, 22,
              ["blanc de poulet", "lait de coco", "pate de curry", "riz basmati", "oignon", "tomate"],
              4.20, 30),
        _meal("Tajine agneau quinoa", 600, 36, 60, 22,
              ["agneau", "abricots secs", "oignon", "quinoa", "amandes", "epices ras el hanout"],
              5.50, 60),
        _meal("Risotto crevettes citron", 580, 32, 65, 20,
              ["riz arborio", "crevettes", "parmesan", "oignon", "bouillon", "citron"],
              5.40, 35),
    ],
    ("sans_gluten", "snack_am"): [
        _meal("Banane et beurre de cacahuete", 280, 8, 35, 12,
              ["banane", "beurre de cacahuete"], 0.80, 2),
        _meal("Skyr fruits rouges", 220, 22, 24, 4,
              ["skyr", "fruits rouges", "miel"], 1.80, 3),
        _meal("Smoothie proteine", 320, 22, 38, 9,
              ["lait demi-ecreme", "banane", "fruits rouges", "proteine whey", "miel"], 2.20, 4),
        _meal("Galettes riz avocat oeuf", 320, 14, 28, 18,
              ["galettes de riz", "avocat", "oeuf poche", "graines de sesame"], 1.80, 8),
        _meal("Yaourt grec amandes miel", 280, 14, 22, 14,
              ["yaourt grec nature", "amandes", "miel"], 1.50, 2),
        _meal("Cottage cheese ananas", 240, 22, 24, 4,
              ["cottage cheese", "ananas frais", "miel"], 2.10, 3),
        _meal("Fruits secs et noix", 300, 8, 32, 16,
              ["noix", "amandes", "raisins secs", "abricots secs"], 1.80, 1),
    ],
    ("sans_gluten", "snack_pm"): [
        _meal("Pomme et amandes", 240, 6, 30, 12,
              ["pomme", "amandes"], 0.80, 1),
        _meal("Skyr fruits frais", 220, 22, 24, 4,
              ["skyr", "myrtilles", "miel"], 1.80, 3),
        _meal("Galettes de riz fromage frais", 280, 12, 32, 10,
              ["galettes de riz", "fromage frais", "concombre", "ciboulette"], 1.60, 5),
        _meal("Smoothie banane lait", 280, 14, 38, 7,
              ["lait demi-ecreme", "banane", "miel", "cannelle"], 1.20, 3),
        _meal("Yaourt grec granola sans gluten", 300, 16, 30, 12,
              ["yaourt grec nature", "granola sans gluten", "miel"], 2.20, 2),
        _meal("Houmous et legumes", 260, 8, 24, 14,
              ["houmous", "carottes", "concombre", "galettes de riz"], 1.60, 5),
        _meal("Oeufs durs pomme amandes", 240, 16, 22, 10,
              ["oeufs durs", "pomme", "amandes"], 1.50, 8),
    ],
}


def build_plan(health_goal: str, diet_type: str) -> dict:
    slots = SLOTS[health_goal]
    days = []
    for d in range(7):
        meals = []
        for slot in slots:
            pool = POOLS[(diet_type, slot)]
            meals.append(pool[d % len(pool)])
        days.append({"day": d + 1, "meals": meals})
    return {"fallback": True, "days": days}


def main() -> None:
    plans: dict[str, dict] = {}
    for hg in HEALTH_GOALS:
        for dt in DIET_TYPES:
            plans[f"{hg}_{dt}"] = build_plan(hg, dt)

    out = Path(__file__).resolve().parent.parent / "app" / "data" / "fallback_plans.json"
    out.write_text(json.dumps(plans, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Genere : {out} ({len(plans)} plans)")


if __name__ == "__main__":
    main()
